package com.capgemini.pokerHands;

public enum CardSchema {
	HIGH_CARD, ONE_PAIR, TWO_PAIRS, THREE_OF_A_KIND, THREE_CARDS_OF_THE_SAME_VALUE, STRAIGHT, FLUSCH, FULL_HOUSE, FOUR_OF_A_KIND, STRAIGT_FLUSCH, ROYAL_FLUSH;
}
